steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-node@v4
    with:
      node-version: 22

  - name: Install Tailwind for root plugin
    run: npm install tailwindcss --no-save

  - name: Install
    working-directory: demo
    run: npm ci

  - name: Build
    working-directory: demo
    run: npm run build
